const names = [
  "SleekDesk",
  "ComfyChair",
  "EcoShelf",
  "NordicTable",
  "BrightLamp",
  "SoftSofa",
  "WallMirror",
  "CozyBed",
  "SpaceRug",
  "ChicCabinet",
  "LoftStool",
  "ClassicClock",
  "PatioSet",
  "KidsBunk",
  "OfficeDrawer",
  "KitchenIsland",
  "BathRack",
  "VanityMirror",
  "DiningSet",
  "BarStool",
  "GardenBench",
  "StorageBox",
  "TVStand",
  "Nightstand",
  "Wardrobe",
  "Bookcase",
  "CoffeeTable",
  "BalconySet",
  "LoungeChair",
  "StudyDesk",
  "FloorLamp",
  "Cushion",
  "WallArt",
  "ShoeRack",
  "LaundryBasket",
  "WineRack",
  "Futon",
  "Curtains",
  "BeanBag",
  "PendantLight"
];

const kinds = ["Outdoor bar table and stool", "Dining table", "Armchair", "Bookcase"];

const images = [
  "https://www.ikea.com/images/fa/88/fa88c91a4ac8db60f44b50cce69166b8.jpg?f=s",
  "https://www.realestate.com.au/news-image/w_1500,h_2000/v1657596856/news-lifestyle-content-assets/wp-content/production/ikea-billy_1500x2000.jpg?_i=AA",
  "https://www.ikea.com/ext/ingkadam/m/7938d3e6281c0a51/original/PH187084.jpg?f=s",
  "https://www.ikea.com/ext/ingkadam/m/784988de0fe4f71b/original/PH176296-crop001.jpg?f=s",
];
